// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "translation": {
    "cm": "cm",
    "daily": "Daily",
    "delete": "Delete",
    "descriptionof": "Description of",
    "done": "Done",
    "fix_results": "Fix Results",
    "g": "g",
    "health_score": "Health Score",
    "info": {
      "left": "left",
      "over": "over"
    },
    "kcal": "kcal",
    "kg": "kg",
    "loader": {
      "title1": "Analyzing daily calories",
      "title2": "Calculating protein intake",
      "title3": "Reviewing activity data",
      "title4": "Analysis complete!"
    },
    "nav": {
      "home": "Home",
      "settings": "Settings"
    },
    "nutfact": {
      "calories": "Calories",
      "carbs": "Carbs",
      "fat": "Fat",
      "protein": "Protein"
    },
    "settings": {
      "accordion_title1": "Personal Information",
      "accordion_title2": "Nutritional Information",
      "cr_height": "Current height",
      "cr_weight": "Current weight",
      "language": "Language",
      "name_input_title": "Enter your name",
      "recalculate": "Recalculate",
      "title_weeks_needed": "Weeks needed to reach goal weight",
      "weeks": "weeks",
      "years": "years"
    },
    "steps": {
      "age": {
        "label": "Your age",
        "title": "Write your age"
      },
      "analyze": "Analyze",
      "api_key": {
        "description": "You can get your api key from",
        "label": "api key",
        "title": "Paste here your gemini API key"
      },
      "continue": "Continue",
      "gender": {
        "female": "Female",
        "male": "Male",
        "title": "Choose your Gender"
      },
      "get_started": "Get Started",
      "goal": {
        "content": {
          "gain": "Muscle Gain",
          "loss": "Weight Loss",
          "maintenance": "Maintenance weight"
        },
        "title": "Your goal"
      },
      "height": {
        "label": "Your height in cm",
        "title": "Write your height"
      },
      "title": "Calorie tracking made easy",
      "weeklykg": {
        "gain": "gain",
        "label": "Slide the range to select",
        "loss": "loss",
        "title": "How much weight do you want to",
        "title2": "per week?"
      },
      "weight": {
        "label": "Your weight in kg",
        "title": "Write your weight"
      },
      "weightgoal": {
        "label": "Write your weight goal in kg",
        "title": "Your weight goal"
      },
      "workouts": {
        "0": "I hardly exercise",
        "2-3": "Sometimes",
        "4-5": "Several times a week",
        "6+": "Professional athlete",
        "title": "How many workouts do you do per week?"
      }
    }
  }
}

export default Resources;
